Cypress.Commands.add('login', (username, password) => {
    cy.get('#menuUserLink').click()
    cy.get('[a-hint="Username"] > .inputContainer > [name="username"]').type(username)
    cy.get('[a-hint="Password"] > .inputContainer > [name="password"]').type(password)
    cy.get('#sign_in_btn').click()
})
Cypress.Commands.add('sendContact', (email, message) =>{
    cy.get('[name=categoryListboxContactUs]')
                .should('be.visible')
                .select(2)  //.select('Laptop')
    cy.get('[name=productListboxContactUs]')
                .should('be.visible')
                .select('HP ENVY - 17t Touch Laptop')
    cy.get('[name=emailContactUs]')
                .should('be.visible')
                .type(email)

    cy.get('[name=subjectTextareaContactUs]').type(message)
    cy.get('#send_btn').click()
})
Cypress.Commands.add('addSpeakersToCart', () => {
    cy.get('#speakersImg').click()
    cy.wait(4000)
    cy.contains('h3','SPEAKERS').should('be.visible')

    cy.get('[class="cell categoryRight"]> ul > :nth-child(3)').click()
    cy.wait(4000)
    cy.get('[name="save_to_cart"]').click()
    cy.get('#checkOutPopUp').should('be.visible')
})
Cypress.Commands.add('add2MicersToCart', () => {
    cy.get('#miceImg').click()
    cy.wait(4000)
    cy.contains('h3','MICE').should('be.visible')

    cy.get('[class="cell categoryRight"]> ul > :nth-child(8)').click()
    cy.wait(4000)
    cy.get('[title="BLUE"]').click()
    cy.get('.plus').click()
    cy.get('[name="save_to_cart"]').click()
    cy.get('#checkOutPopUp').should('be.visible')
})